dmitrygladkov/Diary

c++/c++11/Makefile, c++/c++11/lambda.cxx
=> c++/c++11/lambda: Add Fibonacci test to show lambda utilization

c++/Makefile, c++/memset_perf_test.cxx
=> c++: Add performance testing of the several approaches to set each entry of an array to 0

c++/stl/Makefile, c++/stl/vector.cxx
=> c++/stl/vector: Add testing of the emplace_back and push_back calls

c++/c++11/Makefile, c++/c++11/rvalue_move.cxx
=> c++/c++11: Add test of std::move

ml/scikit-learn/iris.py
=> ml/scikit-learn: Add classical Iris example

ml/scikit-learn/iris.py
=> ml/scikit-learn: Add some imports for the further needs

ml/scikit-learn/nearest_neighbors_class.py
Example is based on Iris dataset
=> ml/scikit-learn: Add an example for the nearest neighbors classification

ml/scikit-learn/knn_classificator_random_gen_data.py
Add yet another example of kNN algorithm. This example run on random generated train and test data set.
Te example is taken from https://habrahabr.ru/post/149693/
=> ml/scikit-learn: Add yet another example of kNN algorithm

ml/scikit-learn/knn_classificator_random_gen_data.py
=> ml/scikit: Fix some typos

ml/anaconda/molecular_bio_dataset.ipynb
=> ml/anaconda: Use another pandas.DataFrame to insert new prepared values

ml/anaconda/molecular_bio_dataset.ipynb
=> ml/anaconda: kNN classification was added

c++/misc/memory_hooks/Makefile, c++/misc/memory_hooks/memory_hooks.cxx
=> c++/misc: Add simple implementation of memory hooks from memory_hooks man page

c++/misc/memory_hooks/Makefile, c++/misc/memory_hooks/memory_hooks.cxx
=> c++/misc: Extend memory hooks to call 2 hooks at once

python/polynomial/polynomial.py
=> python: Add polynomial class

python/polynomial/polynomial.py, python/polynomial/unit_test.py
=> python: Add unit tests and needed operations (add, sub, mul)

python/polynomial/polynomial.py
=> python: Return 0 if all coeffs = 0

.travis.yml, python/polynomial/polynomial.py
=> Enable Travis CI

.travis.yml
=> python: Add python 3.5 and 3.6 in Travis CI yaml script

python/polynomial/polynomial.py, python/polynomial/unit_test.py
=> python: Fix bug for __ne__ and __eq__ methods

c++/numeric_methods/cholesky/cholesky.sln, c++/numeric_methods/cholesky/cholesky/cholesky.vcxproj, c++/numeric_methods/cholesky/cholesky/cholesky.vcxproj.filters, c++/numeric_methods/cholesky/cholesky/cholesky.vcxproj.user, c++/numeric_methods/cholesky/cholesky/main.cpp
=> c++/numeric_methods: Add linear version of Cholesky decomposition

c++/numeric_methods/cholesky/cholesky/main.cpp
=> c++/numeric_methods: Preparations for Cholecky's block algorithm

c++/numeric_methods/cholesky/cholesky/main.cpp
=> c++/numeric_methods: Added implementation of Cholecky block decomposition algorithm

c++/numeric_methods/cholesky/cholesky/main.cpp
=> c++/numeric_methods: Add some fixes + infra

c++/numeric_methods/cholesky/cholesky/main.cpp
=> c++/numeric_methods: Fix all bugs

c++/numeric_methods/cholesky/cholesky/main.cpp
=> c++/parallel_methods: Calculate run time, speedup and efficiency

c++/numeric_methods/BiCGSTAB/BiCGSTAB/BiCGSTAB.sln, c++/numeric_methods/BiCGSTAB/BiCGSTAB/BiCGSTAB/BiCGSTAB.vcxproj, c++/numeric_methods/BiCGSTAB/BiCGSTAB/BiCGSTAB/BiCGSTAB.vcxproj.filters, c++/numeric_methods/BiCGSTAB/BiCGSTAB/BiCGSTAB/BiCGSTAB.vcxproj.user, c++/numeric_methods/BiCGSTAB/BiCGSTAB/BiCGSTAB/main.cpp
=> c++/numeric_methods: Add initial commit for BiCGSTAB

c++/numeric_methods/BiCGSTAB/BiCGSTAB/BiCGSTAB/BiCGSTAB.vcxproj, c++/numeric_methods/BiCGSTAB/BiCGSTAB/BiCGSTAB/main.cpp
=> c++/numeric methods: Add BiCGSTAB implementation

c++/numeric_methods/BiCGSTAB/BiCGSTAB/BiCGSTAB/main.cpp
=> c++/numeric_methods: Add conersation from normal to CRS matrix format

c++/numeric_methods/BiCGSTAB/BiCGSTAB/BiCGSTAB/main.cpp
=> c++/parallel_methods: Add generation of SPD matrix

c++/numeric_methods/CrankNicolson/CrankNicolson/CrankNicolson.vcxproj, c++/numeric_methods/CrankNicolson/CrankNicolson/CrankNicolson.vcxproj.filters, c++/numeric_methods/CrankNicolson/CrankNicolson/main.cpp
=> c++/numeric_methods: Added Crank Nicolson

c++/numeric_methods/CrankNicolson/CrankNicolson/main.cpp
=> c++/patterns: Implemented example of Bridge pattern

c++/Bridge/Bridge.sln, c++/Bridge/Bridge/Bridge.vcxproj, c++/Bridge/Bridge/Bridge.vcxproj.filters, c++/Bridge/Bridge/IMatrix.h, c++/Bridge/Bridge/IMatrixDrawer.h, c++/Bridge/Bridge/main.cpp
=> c++: Add missed files

c++/Bridge/Bridge/IMatrix.h, c++/Bridge/Bridge/IMatrixDrawer.h, c++/Bridge/Bridge/main.cpp
=> c++/patterns: Add Bridge + Decorator

c++/numeric_methods/CrankNicolson/CrankNicolson/main.cpp
=> c++/numeric_methods: Fix some bugs

c++/numeric_methods/CrankNicolson/CrankNicolson/main.cpp
=> c++/numeric_methods: Crank-Nicolson works fine

c++/numeric_methods/CrankNicolson/CrankNicolson/main.cpp
=> c++/numeric_methods: Added testing infrstracture

c++/design_patterns/MatrixExample/MatrixExample.sln, c++/design_patterns/MatrixExample/MatrixExample/MatrixExample.vcxproj, c++/design_patterns/MatrixExample/MatrixExample/MatrixExample.vcxproj.filters, c++/design_patterns/MatrixExample/MatrixExample/MatrixExample.vcxproj.user, c++/design_patterns/MatrixExample/MatrixExample/drawer.h, c++/design_patterns/MatrixExample/MatrixExample/main.cpp, c++/design_patterns/MatrixExample/MatrixExample/matrix.h
=> Implemented Matrix Example

c++/design_patterns/Command/CommandmanagerExample/CommandmanagerExample.sln, c++/design_patterns/Command/CommandmanagerExample/CommandmanagerExample/CommandmanagerExample.vcxproj, c++/design_patterns/Command/CommandmanagerExample/CommandmanagerExample/CommandmanagerExample.vcxproj.filters, c++/design_patterns/Command/CommandmanagerExample/CommandmanagerExample/CommandmanagerExample.vcxproj.user, c++/design_patterns/Command/CommandmanagerExample/CommandmanagerExample/main.cpp
=> Added Command Manager

c++/benchmarks/Makefile, c++/benchmarks/memcpy_bench.c
=> c++/benchmarks: Add memcpy benchmark

python/tools/host_file, python/tools/ps_mem.py
=> python: Add ps_mem script and wrapper

java/thread_pool/ConcurrentThreads.java, java/thread_pool/build.sh, java/thread_pool/run.sh
=> java: Add concurrent threads task

java/thread_pool/ConcurrentThreads_opt.java, java/thread_pool/build.sh, java/thread_pool/build_opt.sh, java/thread_pool/run.sh, java/thread_pool/run_opt.sh
=> java/thread_pool: Add optimized implementation
